apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: rails-k8s-lab-tls
  namespace: default
spec:
  secretName: rails-k8s-lab-tls
  issuerRef:
    name: letsencrypt-prod
  commonName: {{ .Values.hostname }}
  dnsNames:
  - {{ .Values.hostname }}
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - {{ .Values.hostname }}
    - http01:
        ingress: {{ template "rails-k8s-test.fullname" . }}
      domains:
      - {{ .Values.hostname }}
