apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "rails-k8s-test.fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "rails-k8s-test.fullname" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        env:
        - name: DB_HOST
          value: "{{ template "stolon.fullname" . }}-proxy"
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: {{ template "stolon.fullname" . }}
              key: pg_su_password
        - name: SECRET_KEY_BASE
          value: {{ .Values.app.secretKeyBase }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.service.internalPort }}
          initialDelaySeconds: 60 # We need to wait for the database initialization
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.service.internalPort }}
          initialDelaySeconds: 5
          timeoutSeconds: 3
        lifecycle:
          preStop:
            exec:
              command: ["sleep", "30"]
