dependencies:
# - name: postgresql
#   version: 0.15.0
#   repository: https://kubernetes-charts.storage.googleapis.com/
# - name: stolon
#   version: 0.4.1
#   repository: https://kubernetes-charts.storage.googleapis.com/
